# See https://www.elastic.co/guide/en/beats/auditbeat/current/auditbeat-reference-yml.html

# Thanks to "The Windows File Auditing Logging Cheat Sheet" at
#   https://www.malwarearchaeology.com/cheat-sheets

# ==============================================================================

auditbeat.modules:

#------------------------------- file_integrity Module -----------------------

- module: file_integrity
  paths:
  - C:/Program Files
  - C:/Program Files/Internet Explorer
  - C:/Program Files/Common Files
  - C:/Program Files (x86)
  - C:/Program Files (x86) /Common Files
  - C:/ProgramData
  - C:/Windows
  - C:/Windows/System32
  - C:/Windows/System32/Drivers
  - C:/Windows/System32/Drivers/etc
  - C:/Windows/System32/Sysprep
  - C:/Windows/System32/wbem
  - C:/Windows/System32/WindowsPowerShell/v1.0
  - C:/Windows/Web
  - C:/Windows/SysWOW64
  - C:/Windows/SysWOW64/Drivers
  - C:/Windows/SysWOW64/wbem
  - C:/Windows/SysWOW64/WindowsPowerShell/v1.0
  recursive: false

- module: file_integrity
  paths:
  - C:/Boot
  - C:/Perflogs
  - C:/Users/All Users/Microsoft/Windows/Start Menu/Programs/Startup
  - C:/Users/Public
  # todo: wildcards handled?
  # - C:/Users/*/AppData/Local
  # - C:/Users/*/AppData/Local/Temp
  # - C:/Users/*/AppData/LocalLow
  # - C:/Users/*/AppData/Roaming
  - C:/Windows/Scripts
  - C:/Windows/System
  - C:/Windows/System32/GroupPolicy/Machine/Scripts/Startup
  - C:/Windows/System32/GroupPolicy/Machine/Scripts/Shutdown
  - C:/Windows/System32/GroupPolicy/User/Scripts/Logon
  - C:/Windows/System32/GroupPolicy/User/Scripts/Logoff
  - C:/Windows/System32/Repl
  recursive: true

  # examples for exclusions if things are noisy
  # exclude_files:
  # - '(?i)\.blf$'
  # - '(?i)\.dat$'
  # - '(?i)\.lnk$'
  # - '(?i)\.log\w*$'
  # - '(?i)\.mum$'
  # - '(?i)\.regtrans-ms$'
  # - '(?i)\.swp$'
  # - '(?i)\.tmp$'
  # - '(?i)beat\.(lock|yml(\.new)?|db)$'
  # - '(?i)\\(assembly|CatRoot|CbsTemp|databases?|Deleted|diagnostics?|Log(File)?s?|Notifications?|Packages?|Prefetch|schemas?|servicing|Sessions?|SleepStudy|SoftwareDistribution|Tasks?|Temp|tracing|wbem|WinMetadata|WinSAT|WinSxS)\\?'
  # - '(?i)cache'

# TODO: system module is apparently only available in the non-OSS basic license :-(

# - module: system
#   datasets:
#     - host # General host information, e.g. uptime, IPs
#   period: 1m
#   state.period: 1h

# - module: system
#   datasets:
#     - process # Started and stopped processes
#   period: 1s
