# See https://www.elastic.co/guide/en/beats/packetbeat/current/packetbeat-reference-yml.html

# ==============================================================================

# packetbeat.exe requires Npcap (https://nmap.org/npcap/#download) to be installed


#------------------------------- network device ------------------------------

packetbeat.interfaces.device: 0
packetbeat.interfaces.type: pcap
packetbeat.interfaces.snaplen: 65535

#------------------------------- flows ---------------------------------------

packetbeat.flows:
  enabled: true
  timeout: 30s
  period: 10s

#------------------------------- transaction protocols -----------------------

packetbeat.protocols:
- type: icmp
  enabled: true

- type: amqp
  enabled: true
  ports: [5672]

- type: cassandra
  enabled: true
  ports: [9042]

- type: dhcpv4
  enabled: true
  ports: [67, 68]

- type: dns
  enabled: true
  ports: [53]
  include_authorities: true
  include_additionals: true

- type: http
  enabled: true
  ports: [80, 8080, 8000, 5000, 8002]

- type: memcache
  enabled: true
  ports: [11211]

- type: mysql
  enabled: true
  ports: [3306,3307]

- type: pgsql
  enabled: true
  ports: [5432]

- type: redis
  enabled: true
  ports: [6379]

- type: thrift
  enabled: true
  ports: [9090]

- type: mongodb
  enabled: true
  ports: [27017]

- type: nfs
  enabled: true
  ports: [2049]

- type: tls
  enabled: true
  ports:
    - 443   # HTTPS
    - 993   # IMAPS
    - 995   # POP3S
    - 5223  # XMPP over SSL
    - 8443
    - 8883  # Secure MQTT
    - 9243  # Elasticsearch

#------------------------------- monitored processes -------------------------

packetbeat.procs.enabled: true
packetbeat.ignore_outgoing: false
