---
- name: 'create polarproxy user'
  become: yes
  user:
    name: polarproxy
    system: yes

- name: 'create polarproxy dirs'
  become: yes
  file:
    path: '{{ item }}'
    owner: polarproxy
    group: root
    mode: 0775
    state: directory
  loop:
    - /var/log/PolarProxy
    - /opt/PolarProxy

- name: 'download polarproxy'
  become: yes
  unarchive:
    remote_src: yes
    src: 'https://www.netresec.com/?download=PolarProxy'
    dest: '/opt/PolarProxy'
    owner: polarproxy
    group: root

- name: 'add service configuration'
  become: yes
  copy:
    src: 'PolarProxy.service'
    dest: '/etc/systemd/system/'

- name: 'enable and start polarproxy service'
  become: yes
  systemd:
    name: PolarProxy
    enabled: yes
    state: started

- name: 'wait for polarproxy to generate cert'
  wait_for:
    path: /var/log/PolarProxy/polarproxy.cer

- name: 'copy cer to shared folder'
  copy:
    remote_src: yes
    src: /var/log/PolarProxy/polarproxy.cer
    dest: /vagrant/

- name: 'redirect 443 traffic to polarproxy'
  become: yes
  iptables:
    table: nat
    chain: PREROUTING
    action: insert
    in_interface: eth1
    protocol: tcp
    jump: REDIRECT
    destination_port: '443'
    to_ports: '10443'

- name: 'redirect https traffic to tor'
  become: yes
  iptables:
    table: nat
    chain: OUTPUT
    protocol: tcp
    uid_owner: polarproxy
    jump: DNAT
    destination_port: '443'
    to_destination: '192.168.1.1:9040'

# TODO move this to its own role, together with all IPtables stuff
- name: 'save iptables status'
  become: yes
  shell: 'iptables-save > /etc/iptables.rules'

- name: 'load iptables at reboot'
  become: yes
  cron:
    name: 'load iptables'
    reboot: yes
    job: '/usr/sbin/iptables-restore < /etc/iptables.rules'

# Polarproy rotates the pcaps every hour, there's no way to change that,
# to force the rotation we just restart the daemon
- name: 'restart polar proxy every minute'
  become: yes
  cron:
    name: 'restart PolarProxy'
    minute: '*/2'
    job: 'systemctl restart PolarProxy'
