---
- hosts: router
  any_errors_fatal: true
  become: true
  gather_facts: false
  roles:
    - 'robertdebock.bootstrap'

- hosts: router
  any_errors_fatal: true
  roles:
    # - 'docker'
    # - 'docker-compose'
    - 'polarproxy'
    - 'tor_proxy'
    # - 'malcolm'


