# See https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-system.html
#     https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-reference-yml.html

# ==============================================================================

filebeat.modules:

#------------------------------- System Module -------------------------------

- module: system
  syslog:
    enabled: true
  auth:
    enabled: true
