# See https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-reference-yml.html

# ==============================================================================

metricbeat.config.modules:
  path: ${path.config}/conf.d/*.yml
  reload.period: 10s
  reload.enabled: false

metricbeat.max_start_delay: 10s

metricbeat.modules:

#------------------------------- System Module -------------------------------

- module: system
  period: 30s
  metricsets:
    - cpu             # CPU usage
    - load            # CPU load averages
    - memory          # Memory usage
    - network         # Network IO
    - process         # Per process metrics
    - process_summary # Process summary
    - uptime          # System Uptime
    - diskio          # Disk IO
  enabled: true
  processes: ['.*']
  process.include_top_n:
    enabled: true
    by_cpu: 10
    by_memory: 10

  cpu.metrics:  ["percentages"]
  core.metrics: ["percentages"]

- module: system
  period: 1m
  metricsets:
    - filesystem     # File system usage for each mountpoint
    - fsstat         # File system summary metrics
  processors:
  - drop_event.when.regexp:
      system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib|boot)($|/)'
