---
all:
  hosts:
    router:
      ansible_host: 127.0.0.1
      ansible_port: 2200
      ansible_user: vagrant
      ansible_ssh_private_key_file: ../.vagrant/machines/router/virtualbox/private_key
